//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace folderchat.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1234")]
        public string OpenAI_BaseUrl {
            get {
                return ((string)(this["OpenAI_BaseUrl"]));
            }
            set {
                this["OpenAI_BaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("abc")]
        public string OpenAI_ApiKey {
            get {
                return ((string)(this["OpenAI_ApiKey"]));
            }
            set {
                this["OpenAI_ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int Chat_FontSize {
            get {
                return ((int)(this["Chat_FontSize"]));
            }
            set {
                this["Chat_FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_Theme {
            get {
                return ((int)(this["UI_Theme"]));
            }
            set {
                this["UI_Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1234/v1")]
        public string Embedding_Url {
            get {
                return ((string)(this["Embedding_Url"]));
            }
            set {
                this["Embedding_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text-embedding-embeddinggemma-300m")]
        public string Embedding_Model {
            get {
                return ((string)(this["Embedding_Model"]));
            }
            set {
                this["Embedding_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("float")]
        public string Embedding_EncodingFormat {
            get {
                return ((string)(this["Embedding_EncodingFormat"]));
            }
            set {
                this["Embedding_EncodingFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Embedding_Dimensions {
            get {
                return ((int)(this["Embedding_Dimensions"]));
            }
            set {
                this["Embedding_Dimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderTree_State {
            get {
                return ((string)(this["FolderTree_State"]));
            }
            set {
                this["FolderTree_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAI_ModelList {
            get {
                return ((string)(this["OpenAI_ModelList"]));
            }
            set {
                this["OpenAI_ModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAI_SelectedModel {
            get {
                return ((string)(this["OpenAI_SelectedModel"]));
            }
            set {
                this["OpenAI_SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public int RAG_ContextLength {
            get {
                return ((int)(this["RAG_ContextLength"]));
            }
            set {
                this["RAG_ContextLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int RAG_ChunkSize {
            get {
                return ((int)(this["RAG_ChunkSize"]));
            }
            set {
                this["RAG_ChunkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int RAG_ChunkOverlap {
            get {
                return ((int)(this["RAG_ChunkOverlap"]));
            }
            set {
                this["RAG_ChunkOverlap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseNativeEmbedding {
            get {
                return ((bool)(this["UseNativeEmbedding"]));
            }
            set {
                this["UseNativeEmbedding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpenAI Compatible")]
        public string API_Provider {
            get {
                return ((string)(this["API_Provider"]));
            }
            set {
                this["API_Provider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("claude")]
        public string ClaudeCode_CLIPath {
            get {
                return ((string)(this["ClaudeCode_CLIPath"]));
            }
            set {
                this["ClaudeCode_CLIPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sonnet")]
        public string ClaudeCode_Model {
            get {
                return ((string)(this["ClaudeCode_Model"]));
            }
            set {
                this["ClaudeCode_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RAG_TopKChunks {
            get {
                return ((int)(this["RAG_TopKChunks"]));
            }
            set {
                this["RAG_TopKChunks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int RAG_MaxContextLength {
            get {
                return ((int)(this["RAG_MaxContextLength"]));
            }
            set {
                this["RAG_MaxContextLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MCP_Servers {
            get {
                return ((string)(this["MCP_Servers"]));
            }
            set {
                this["MCP_Servers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string PreferredLanguage {
            get {
                return ((string)(this["PreferredLanguage"]));
            }
            set {
                this["PreferredLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("API")]
        public string EmbeddingMethod {
            get {
                return ((string)(this["EmbeddingMethod"]));
            }
            set {
                this["EmbeddingMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmbeddingGGUFModel {
            get {
                return ((string)(this["EmbeddingGGUFModel"]));
            }
            set {
                this["EmbeddingGGUFModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("API")]
        public string ChatMethod {
            get {
                return ((string)(this["ChatMethod"]));
            }
            set {
                this["ChatMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatGGUFModel {
            get {
                return ((string)(this["ChatGGUFModel"]));
            }
            set {
                this["ChatGGUFModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azure AI Foundry")]
        public string AzureAI_ProviderName {
            get {
                return ((string)(this["AzureAI_ProviderName"]));
            }
            set {
                this["AzureAI_ProviderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://YOUR_RESOURCE_NAME.openai.azure.com")]
        public string AzureAI_ApiUrl {
            get {
                return ((string)(this["AzureAI_ApiUrl"]));
            }
            set {
                this["AzureAI_ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2025-01-01-preview")]
        public string AzureAI_ApiVersion {
            get {
                return ((string)(this["AzureAI_ApiVersion"]));
            }
            set {
                this["AzureAI_ApiVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureAI_ApiKey {
            get {
                return ((string)(this["AzureAI_ApiKey"]));
            }
            set {
                this["AzureAI_ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureAI_ModelList {
            get {
                return ((string)(this["AzureAI_ModelList"]));
            }
            set {
                this["AzureAI_ModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureAI_SelectedModel {
            get {
                return ((string)(this["AzureAI_SelectedModel"]));
            }
            set {
                this["AzureAI_SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://openrouter.ai/api/v1")]
        public string OpenRouter_ApiUrl {
            get {
                return ((string)(this["OpenRouter_ApiUrl"]));
            }
            set {
                this["OpenRouter_ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenRouter_ApiKey {
            get {
                return ((string)(this["OpenRouter_ApiKey"]));
            }
            set {
                this["OpenRouter_ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenRouter_ModelList {
            get {
                return ((string)(this["OpenRouter_ModelList"]));
            }
            set {
                this["OpenRouter_ModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenRouter_SelectedModel {
            get {
                return ((string)(this["OpenRouter_SelectedModel"]));
            }
            set {
                this["OpenRouter_SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11434")]
        public string Ollama_ApiUrl {
            get {
                return ((string)(this["Ollama_ApiUrl"]));
            }
            set {
                this["Ollama_ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Ollama_ModelList {
            get {
                return ((string)(this["Ollama_ModelList"]));
            }
            set {
                this["Ollama_ModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Ollama_SelectedModel {
            get {
                return ((string)(this["Ollama_SelectedModel"]));
            }
            set {
                this["Ollama_SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.openai.com/v1")]
        public string OpenAIAPI_ApiUrl {
            get {
                return ((string)(this["OpenAIAPI_ApiUrl"]));
            }
            set {
                this["OpenAIAPI_ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAIAPI_ApiKey {
            get {
                return ((string)(this["OpenAIAPI_ApiKey"]));
            }
            set {
                this["OpenAIAPI_ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAIAPI_ModelList {
            get {
                return ((string)(this["OpenAIAPI_ModelList"]));
            }
            set {
                this["OpenAIAPI_ModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAIAPI_SelectedModel {
            get {
                return ((string)(this["OpenAIAPI_SelectedModel"]));
            }
            set {
                this["OpenAIAPI_SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://generativelanguage.googleapis.com/v1beta")]
        public string Gemini_ApiUrl {
            get {
                return ((string)(this["Gemini_ApiUrl"]));
            }
            set {
                this["Gemini_ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Gemini_ApiKey {
            get {
                return ((string)(this["Gemini_ApiKey"]));
            }
            set {
                this["Gemini_ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Gemini_ModelList {
            get {
                return ((string)(this["Gemini_ModelList"]));
            }
            set {
                this["Gemini_ModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Gemini_SelectedModel {
            get {
                return ((string)(this["Gemini_SelectedModel"]));
            }
            set {
                this["Gemini_SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRAG {
            get {
                return ((bool)(this["UseRAG"]));
            }
            set {
                this["UseRAG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClaudeCode_SupportsSystemRole {
            get {
                return ((bool)(this["ClaudeCode_SupportsSystemRole"]));
            }
            set {
                this["ClaudeCode_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AzureAI_SupportsSystemRole {
            get {
                return ((bool)(this["AzureAI_SupportsSystemRole"]));
            }
            set {
                this["AzureAI_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenRouter_SupportsSystemRole {
            get {
                return ((bool)(this["OpenRouter_SupportsSystemRole"]));
            }
            set {
                this["OpenRouter_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ollama_SupportsSystemRole {
            get {
                return ((bool)(this["Ollama_SupportsSystemRole"]));
            }
            set {
                this["Ollama_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenAIAPI_SupportsSystemRole {
            get {
                return ((bool)(this["OpenAIAPI_SupportsSystemRole"]));
            }
            set {
                this["OpenAIAPI_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Gemini_SupportsSystemRole {
            get {
                return ((bool)(this["Gemini_SupportsSystemRole"]));
            }
            set {
                this["Gemini_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenAI_SupportsSystemRole {
            get {
                return ((bool)(this["OpenAI_SupportsSystemRole"]));
            }
            set {
                this["OpenAI_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.anthropic.com/v1")]
        public string Claude_ApiUrl {
            get {
                return ((string)(this["Claude_ApiUrl"]));
            }
            set {
                this["Claude_ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Claude_ApiKey {
            get {
                return ((string)(this["Claude_ApiKey"]));
            }
            set {
                this["Claude_ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Claude_ModelList {
            get {
                return ((string)(this["Claude_ModelList"]));
            }
            set {
                this["Claude_ModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Claude_SelectedModel {
            get {
                return ((string)(this["Claude_SelectedModel"]));
            }
            set {
                this["Claude_SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Claude_SupportsSystemRole {
            get {
                return ((bool)(this["Claude_SupportsSystemRole"]));
            }
            set {
                this["Claude_SupportsSystemRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAPIServer {
            get {
                return ((bool)(this["EnableAPIServer"]));
            }
            set {
                this["EnableAPIServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11550")]
        public int APIServerPort {
            get {
                return ((int)(this["APIServerPort"]));
            }
            set {
                this["APIServerPort"] = value;
            }
        }
    }
}
